//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datenManipulation.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public int ID { get; set; }
        public int ID_Kategorie { get; set; }
        public string Bezeichnung { get; set; }
        public decimal Preis { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
    }
}
