
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace innovation4austria.dataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class bills
{

    public bills()
    {

        this.billdetails = new HashSet<billdetails>();

    }


    public int id { get; set; }

    public System.DateTime date { get; set; }

    public int portaluser_id { get; set; }



    public virtual ICollection<billdetails> billdetails { get; set; }

    public virtual portalusers portalusers { get; set; }

}

}
