
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace innovation4austria.dataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class bookings
{

    public bookings()
    {

        this.billdetails = new HashSet<billdetails>();

        this.bookingreversals = new HashSet<bookingreversals>();

    }


    public int id { get; set; }

    public int room_id { get; set; }

    public int portaluser_id { get; set; }

    public System.DateTime date { get; set; }



    public virtual ICollection<billdetails> billdetails { get; set; }

    public virtual ICollection<bookingreversals> bookingreversals { get; set; }

    public virtual portalusers portalusers { get; set; }

    public virtual rooms rooms { get; set; }

}

}
