
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace innovation4austria.dataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class facilities
{

    public facilities()
    {

        this.rooms = new HashSet<rooms>();

    }


    public int id { get; set; }

    public string facilityname { get; set; }

    public string zip { get; set; }

    public string city { get; set; }

    public string street { get; set; }

    public string number { get; set; }



    public virtual ICollection<rooms> rooms { get; set; }

}

}
