
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace innovation4austria.dataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class rooms
{

    public rooms()
    {

        this.bookings = new HashSet<bookings>();

        this.furnishings = new HashSet<furnishings>();

    }


    public int id { get; set; }

    public int facility_id { get; set; }

    public string description { get; set; }

    public decimal price { get; set; }



    public virtual ICollection<bookings> bookings { get; set; }

    public virtual facilities facilities { get; set; }

    public virtual ICollection<furnishings> furnishings { get; set; }

}

}
